USE [master]
GO
/****** Object:  Database [MyData]    Script Date: 8/11/2019 5:43:07 PM ******/
CREATE DATABASE [MyData]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MyData', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\MyData.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MyData_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\MyData_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [MyData] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MyData] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MyData] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MyData] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MyData] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MyData] SET ARITHABORT OFF 
GO
ALTER DATABASE [MyData] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MyData] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MyData] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MyData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MyData] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MyData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MyData] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MyData] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MyData] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MyData] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MyData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MyData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MyData] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MyData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MyData] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MyData] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MyData] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MyData] SET RECOVERY FULL 
GO
ALTER DATABASE [MyData] SET  MULTI_USER 
GO
ALTER DATABASE [MyData] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MyData] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MyData] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MyData] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MyData] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MyData] SET QUERY_STORE = OFF
GO
USE [MyData]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [MyData]
GO
/****** Object:  Table [dbo].[AccountType]    Script Date: 8/11/2019 5:43:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AccountType](
	[ID] [uniqueidentifier] NOT NULL,
	[AccountTypeName] [nvarchar](50) NOT NULL,
	[AccountTypeCode] [nvarchar](50) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[ModifyDate] [datetime] NOT NULL,
	[ModifyBy] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_AccountType] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[StaffInfo]    Script Date: 8/11/2019 5:43:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[StaffInfo](
	[ID] [uniqueidentifier] NOT NULL,
	[EmployeeID] [nvarchar](50) NOT NULL,
	[DivisionName] [nvarchar](50) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](255) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[ModifyDate] [datetime] NOT NULL,
	[ModifyBy] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_StaffInfo] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[UserAccount]    Script Date: 8/11/2019 5:43:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserAccount](
	[ID] [uniqueidentifier] NOT NULL,
	[AccountTypeFK] [uniqueidentifier] NOT NULL,
	[StaffInfoFK] [uniqueidentifier] NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](500) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[ModifyDate] [datetime] NOT NULL,
	[ModifyBy] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_UserAccount] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[UserAccount]  WITH CHECK ADD  CONSTRAINT [FK__UserAccou__AccountType] FOREIGN KEY([AccountTypeFK])
REFERENCES [dbo].[AccountType] ([ID])
GO
ALTER TABLE [dbo].[UserAccount] CHECK CONSTRAINT [FK__UserAccou__AccountType]
GO
ALTER TABLE [dbo].[UserAccount]  WITH CHECK ADD  CONSTRAINT [FK__UserAccou__StaffInfo] FOREIGN KEY([StaffInfoFK])
REFERENCES [dbo].[StaffInfo] ([ID])
GO
ALTER TABLE [dbo].[UserAccount] CHECK CONSTRAINT [FK__UserAccou__StaffInfo]
GO
USE [master]
GO
ALTER DATABASE [MyData] SET  READ_WRITE 
GO
